spring:
  security:
    enabled: false
  data:
    mongodb:
      uri: ${MONGO_URI}

management:
  security:
    enabled: false

server:
  port: 8081

auth:
  url: ${AUTH_SERVER:localhost:8080}